Docker 2
Otus-DevOps-2021-02/Kvaido_microservices pull request #1
Opened 2021-06-03 18:38 UTC by Kvaido

2021-06-04 08:23 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу, дз возвращаю на доработку.

2021-06-04 08:23 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Лушче попробовать на Ubuntu 16.04

2021-06-04 13:16 UTC, Kvaido commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Что-то не сработало.

2021-06-07 08:55 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все задания выполнены корректно, апрув!=)

2021-06-07 08:55 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:16.04
Так сработало ведь =)

2021-06-07 18:11 UTC, Kvaido commented on docker-monolith/Dockerfile
> +FROM ubuntu:16.04
Там пришлось еще одну строку укоротить :)

2021-06-07 18:11 UTC, merged